name: Update Test Badge

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    # Run daily at 9 AM UTC
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  test-and-badge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'yarn'
        cache-dependency-path: yarn.lock
        
    - name: Install dependencies
      run: |
        yarn install --frozen-lockfile
        
    - name: Run tests and generate badge
      run: |
        yarn test:badge
        
    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Commit and push changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add README.md test-results.json public/test-results.html
        git commit -m "🧪 Update test badge and results [skip ci]" || exit 0
        git push origin HEAD:main
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          test-results.json
          public/test-results.html
          coverage/
        retention-days: 30
        
    - name: Comment PR with test results
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          
          try {
            const resultsPath = 'test-results.json';
            const results = JSON.parse(fs.readFileSync(resultsPath, 'utf8'));
            
            const passRate = results.passRate;
            const statusIcon = passRate >= 80 ? '✅' : passRate >= 60 ? '⚠️' : '❌';
            
            const comment = `## ${statusIcon} Test Results
            
            | Metric | Value |
            |--------|-------|
            | **Total Tests** | ${results.total} |
            | **Passing** | ${results.passing} ✅ |
            | **Failing** | ${results.failing} ❌ |
            | **Pass Rate** | ${results.passRate}% |
            
            ${passRate >= 80 ? '🎉 Great job! All tests are passing.' : 
              passRate >= 60 ? '⚠️ Some tests are failing. Please review.' : 
              '❌ Multiple test failures detected. Please fix before merging.'}
            `;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
          } catch (error) {
            console.log('Could not read test results:', error.message);
          }